var db = require("./models");

var allListings =[];
allListings.push({
  type: 'Apartment',
  bedrooms: 2,
  bathrooms: 1.0,
  leaseLength: 'One Year',
  squareFeet: '1,015',
  parkingType: 'Garage',
  clothesWasher: 'No Hookup',
  clothesDryer: 'No Hookup',
  laundryRoomAndFacility: 'On site',
  listingName: 'Delmas Park Apartments',
  address: '350 Bird Avenue, San Jose, CA 95126',
  propertyContactName: 'EAH Housing - Vanessa Abbott',
  propertyContactPhoneNumber: '408-993-9119',
  propertyContactEmail: 'dp-manager@eahhousing.org',
  propertyContactWebsite: 'http://delmasparkapartments.rentaladdress.com/',
  speakSpanish: 'Yes',
  speakVietnamese: 'No',
  acceptsSection8: 'Yes',
  taxCreditProperty: 'Yes',
  subsidizedRentOk: 'No',
  seniorsOnly: 'No',
  cats: 'No',
  dogs: 'No',
  securityDeposit: '$700',
  applicationFee: '$30 per adult',
  dateAvailable: 'Waiting List',
  image: 'http://www.delmasparkapts.com/properties/1729/property_photos/20347/S_450_WIDTH_extension_jpg_q_90__v2_Delmas_Park1_final_JPG.jpg',
  incomeBasedRent: 'Yes',
  rentAmount: '$0 - $1,499',
  latitude: 37.3242903,
  longitude: -121.89968379999999
});
allListings.push({
  type: 'Studio',
  bedrooms: 0,
  bathrooms: 1.0,
  leaseLength: 'One Year',
  squareFeet: '625',
  parkingType: 'Garage',
  clothesWasher: 'No Hookup',
  clothesDryer: 'No Hookup',
  laundryRoomAndFacility: 'On site',
  listingName: 'Delmas Park Apartments',
  address: '350 Bird Avenue, San Jose, CA 95126',
  propertyContactName: 'EAH Housing - Vanessa Abbott',
  propertyContactPhoneNumber: '408-993-9119',
  propertyContactEmail: 'dp-manager@eahhousing.org',
  propertyContactWebsite: 'http://delmasparkapartments.rentaladdress.com/',
  speakSpanish: 'Yes',
  speakVietnamese: 'No',
  acceptsSection8: 'Yes',
  taxCreditProperty: 'Yes',
  subsidizedRentOk: 'No',
  seniorsOnly: 'No',
  cats: 'No',
  dogs: 'No',
  securityDeposit: '$500',
  applicationFee: '$30 per adult',
  dateAvailable: 'Waiting List',
  image: 'http://www.delmasparkapts.com/properties/1729/property_photos/20347/S_450_WIDTH_extension_jpg_q_90__v2_Delmas_Park1_final_JPG.jpg',
  incomeBasedRent: 'Yes',
  rentAmount: '$0 - $979',
  latitude: 37.3242903,
  longitude: -121.89968379999999
});
allListings.push({
  type: 'Apartment',
  bedrooms: 1,
  bathrooms: 1.0,
  leaseLength: 'One Year',
  squareFeet: '715',
  parkingType: 'Garage',
  clothesWasher: 'No Hookup',
  clothesDryer: 'No Hookup',
  laundryRoomAndFacility: 'On Site',
  listingName: 'Villa Torre Apartments',
  address: '955 South Sixth Street, San Jose, CA 95112',
  propertyContactName: 'CARE - Jayme Calvo',
  propertyContactPhoneNumber: '408-292-4600',
  propertyContactEmail: 'villatorre@caremgt.com',
  propertyContactWebsite: 'http://www.caremgt.com/',
  speakSpanish: 'No',
  speakVietnamese: 'No',
  acceptsSection8: 'Yes',
  taxCreditProperty: 'No',
  subsidizedRentOk: 'No',
  seniorsOnly: 'No',
  cats: 'No',
  dogs: 'No',
  securityDeposit: '$1,232',
  applicationFee: '$33 per adult',
  dateAvailable: 'Waiting List',
  image: 'http://www.caremgt.com/images/communities/villa_torre/photo_6.jpg',
  incomeBasedRent: 'No',
  rentAmount: '$1,232',
  latitude: 37.3245349,
  longitude: -121.87495030000002
});
allListings.push({
  type: 'Apartment',
  bedrooms: 1,
  bathrooms: 1.0,
  leaseLength: 'One Year',
  squareFeet: 'N/A',
  parkingType: 'Garage',
  clothesWasher: 'No Hookup',
  clothesDryer: 'No Hookup',
  laundryRoomAndFacility: 'On site',
  listingName: 'Belovida At Newbury Park Apartments',
  address: '1777 Newbury Park Drive, San Jose, CA 95133 ',
  propertyContactName: 'EAH Housing',
  propertyContactPhoneNumber: '408-263-8484',
  propertyContactEmail: 'bnp-manager@eahhousing.org',
  propertyContactWebsite: 'http://eahhousing.org',
  speakSpanish: 'Yes',
  speakVietnamese: 'Yes',
  acceptsSection8: 'Yes',
  taxCreditProperty: 'Yes',
  subsidizedRentOk: 'No',
  seniorsOnly: 'Yes',
  cats: 'Yes',
  dogs: 'Yes',
  securityDeposit: '$500',
  applicationFee: '$46 per adult',
  dateAvailable: 'Waiting List',
  image: 'https://eahhousing.blob.core.windows.net/assets/BNP_LivingRoom_2012WEB.jpg',
  incomeBasedRent: 'No',
  rentAmount: '$1,002',
  latitude: 37.3665838,
  longitude: -121.867343
});
allListings.push({
  type: 'Apartment',
  bedrooms: 0,
  bathrooms: 1.0,
  leaseLength: 'One Year',
  squareFeet: '476',
  parkingType: 'Off street',
  clothesWasher: 'No Hookup',
  clothesDryer: 'No Hookup',
  laundryRoomAndFacility: 'On site',
  listingName: 'Casa De Los Amigos',
  address: '967 Lundy Street, San Jose, CA 95133 ',
  propertyContactName: 'Eden Housing - Verenice Olvera',
  propertyContactPhoneNumber: '408-937-0794',
  propertyContactEmail: 'No Email',
  propertyContactWebsite: 'www.edenhousing.org',
  speakSpanish: 'No',
  speakVietnamese: 'No',
  acceptsSection8: 'No',
  taxCreditProperty: 'No',
  subsidizedRentOk: 'No',
  seniorsOnly: 'No',
  cats: 'No',
  dogs: 'No',
  securityDeposit: '$810',
  applicationFee: 'None',
  dateAvailable: 'Waiting List',
  image: 'http://www.socialserve.com/WebFile?id=662967',
  incomeBasedRent: 'Yes',
  rentAmount: '$0 - $810',
  latitude: 37.3721286,
  longitude: -121.8735691
});

// populate eaching listing

db.Listing.remove({}, function(err, listings){

  db.Listing.create(allListings, function(err, listings){
    if (err) { return console.log('ERROR', err); }
    console.log("all listings:", listings);
    console.log("created", listings.length, "listings");
    process.exit();
  });

});
